import Head from 'next/head'
import Image from 'next/image'
import { CaretDown } from 'phosphor-react'
import { LoginForm } from './LoginForm'

export const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex max-h-min flex-col items-center justify-center bg-slate-100">
        <div className="grid grid-cols-1 gap-8 pb-8 md:grid-cols-2">
          <div className="mt-[3rem] hidden h-[40rem] w-80 items-center justify-center rounded-3xl bg-slate-700 font-bold text-white shadow-md md:flex">
            NO MOCKUP PHONE YET
          </div>
          <div className="container mx-auto mt-[6rem] w-[21.875rem]">
            <LoginForm />
            <div className="md:text-md mt-2 flex justify-center gap-1 bg-transparent p-5 text-sm md:border md:bg-white">
              <p>Don&apos;t have an account?</p>
              <a href="#" className="text-blue-500 hover:underline">
                Sign up
              </a>
            </div>

            <div>
              <p className="m-5 text-center text-sm">Get the app.</p>
              <div className="flex justify-center gap-2">
                <Image
                  src="https://instagram.com/static/images/appstore-install-badges/badge_ios_portuguese-brazilian-pt_br.png/68006a2bb372.png"
                  alt=""
                  layout="fixed"
                  height={40}
                  width={140}
                />
                <Image
                  src="https://instagram.com/static/images/appstore-install-badges/badge_android_portuguese_brazilian-pt_BR.png/2f2a0c05b2f3.png"
                  alt=""
                  layout="fixed"
                  height={40}
                  width={140}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="mx-auto w-full items-center justify-center text-xs text-gray-500 md:w-1/2 ">
        <div className="mt-6 flex flex-wrap justify-center [&>*]:mx-1 [&>*]:mb-3 [&>*]:px-1">
          <a href="#">Meta</a>
          <a href="#">About</a>
          <a href="#">Blog</a>
          <a href="#">Jobs</a>
          <a href="#">Help</a>
          <a href="#">API</a>
          <a href="#">Privacy</a>
          <a href="#">Terms</a>
          <a href="#">Top Accounts</a>
          <a href="#">Hashtags</a>
          <a href="#">Locations</a>
          <a href="#">Instagram Lite</a>
          <a href="#">Contact Uploading & Non-Users</a>
          <a href="#">Dance</a>
          <a href="#">Food & Drink</a>
          <a href="#">Home & Garden</a>
          <a href="#">Music</a>
          <a href="#">Visual Arts</a>
        </div>
        <div className="my-4 flex justify-center gap-[11px] text-gray-500">
          <p>
            English{' '}
            <span className="inline-flex">
              <CaretDown size={12} />
            </span>
          </p>
          <p>© 2022 Instagram from Meta</p>
        </div>
      </footer>
    </>
  )
}
