import Head from 'next/head'
import Image from 'next/image'
import { LoginForm } from './LoginForm'

export const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex flex-col items-center justify-center min-h-screen bg-slate-100">
        <div className="grid grid-cols-1 md:grid-cols-2 h-screen w-full ">
          <div className="min-h-full bg-slate-700"></div>
          <div className="container h-96 w-96 m-auto">
            <LoginForm />
            <div className="bg-white border mt-2 p-5 flex justify-center gap-1">
              <p>Don&apos;t have an account?</p>
              <a href="#" className="text-blue-500 hover:underline">
                Sign up
              </a>
            </div>

            <div>
              <p className="text-xs text-center m-5">Get the app.</p>
              <div className="flex justify-center gap-2">
                <Image
                  src="https://instagram.com/static/images/appstore-install-badges/badge_ios_portuguese-brazilian-pt_br.png/68006a2bb372.png"
                  alt=""
                  layout="fixed"
                  height={40}
                  width={140}
                />
                <Image
                  src="https://instagram.com/static/images/appstore-install-badges/badge_android_portuguese_brazilian-pt_BR.png/2f2a0c05b2f3.png"
                  alt=""
                  layout="fixed"
                  height={40}
                  width={140}
                />
              </div>
            </div>
          </div>
          {/* {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>} */}
        </div>
      </main>
    </>
  )
}
